### ISSUE TITLE
Receiver worker seen to fail after reporting a successful test

### ISSUE THREAD

**Issue by k-wall** [maestro-performance/maestro-java#101] opened 2018-07-21 16:21 UTC
With a test scenario of 250 senders and 250 receivers I ran into the following issue.  A receiver worker failed with a NPE.  The logs suggest that the worker actually completed the test successfully, but then there was another condition that caused the worker to have failed.  The watch dog code then threw the NPE because worker state info lacked an exception.  I don't think the true underlying cause is logged. 

```
15:57:12,404 org.maestro.worker.common.ConcurrentWorkerManager - Stopping test execution after a peer reported a test success
...
15:57:13,000 org.maestro.client.MaestroReceiverClient - Sending the test failure notification from org.maestro.client.MaestroReceiverClient@7bc2e68f
Exception in thread "Thread-26" java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at org.maestro.worker.common.WorkerWatchdog.run(WorkerWatchdog.java:115)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by orpiske** [comment] 2018-07-21 16:39
Thanks @k-wall. Was this w/ 1.3.4 or with 1.3.5?

**Comment by k-wall** [comment] 2018-07-21 16:45
It was a build from my fork of devel which was at 51fab5ffcb4ba5e8ae0bc4b1456277d65a6af5e3 (i.e late 2018-08-20 UTC).

**Comment by orpiske** [comment] 2018-07-21 16:52
@k-wall the attached logs seem to be from the front-end. Would you have the logs on the receiver worker? I am specifically looking for a line that says something like this: 

"Unexpected error while running the receiver worker"

**Comment by orpiske** [comment] 2018-07-21 17:05
My secondary guess is that the code might be missing the volatile flag here: https://github.com/maestro-performance/maestro-java/blob/devel/maestro-workers/maestro-worker-jms/src/main/java/org/maestro/worker/jms/JMSReceiverWorker.java#L55

**Comment by k-wall** [comment] 2018-07-23 07:43
@orpiske yes, I agree that lack of atomicity and/or unsafe publication could be responsible for this problem.

**Comment by orpiske** [comment] 2018-07-23 11:18
There were a couple of problems with the old approach. First it was that the code could send the notifications before the flush occurring and the second was this potential lack of atomicity/unsafe publication caused by the lack of volatile. 

I ran several tests w/ the code on the linked PR over the weekend and it seems to be stable enough to move to the devel branch for additional testing. 

I am closing the ticket, but we can certainly reopen it if the problem remains. Thanks!

**Closed by orpiske** 2018-07-23 11:18 UTC
